// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBph3JunCLC-HhvzpRSqDCF9dbeHRoyOgU',
    appId: '1:538347695231:web:efb3074e4a75c7d82e234a',
    messagingSenderId: '538347695231',
    projectId: 'social-authentication-te-93cc1',
    authDomain: 'social-authentication-te-93cc1.firebaseapp.com',
    storageBucket: 'social-authentication-te-93cc1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-08Tq37Ur7m2P2Ff3CIxNCrayIRSwWio',
    appId: '1:538347695231:android:4749802c9e231fdd2e234a',
    messagingSenderId: '538347695231',
    projectId: 'social-authentication-te-93cc1',
    storageBucket: 'social-authentication-te-93cc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyAbTIqrzoBTShisaVfteUItFdZ5GY8sz7E',
    appId: '1:538347695231:ios:773e616508dc3ba62e234a',
    messagingSenderId: '538347695231',
    projectId: 'social-authentication-te-93cc1',
    storageBucket: 'social-authentication-te-93cc1.firebasestorage.app',
    iosClientId: '538347695231-b3lbg1go8fk944cc19gtg21gofmbqbsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialAuthenticationFlutterStructure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbTIqrzoBTShisaVfteUItFdZ5GY8sz7E',
    appId: '1:538347695231:ios:773e616508dc3ba62e234a',
    messagingSenderId: '538347695231',
    projectId: 'social-authentication-te-93cc1',
    storageBucket: 'social-authentication-te-93cc1.firebasestorage.app',
    iosClientId: '538347695231-b3lbg1go8fk944cc19gtg21gofmbqbsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialAuthenticationFlutterStructure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBph3JunCLC-HhvzpRSqDCF9dbeHRoyOgU',
    appId: '1:538347695231:web:ee260afbbf7805ea2e234a',
    messagingSenderId: '538347695231',
    projectId: 'social-authentication-te-93cc1',
    authDomain: 'social-authentication-te-93cc1.firebaseapp.com',
    storageBucket: 'social-authentication-te-93cc1.firebasestorage.app',
  );
}
